### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kroggen** [aergoio/athena-ide-atom#10]
Version 0.5.2
On Mac

```
> secp256k1@3.8.0 install /private/var/folders/3b/81d70l4s7_x_rrfjnzzbmgv00000gn/T/apm-install-dir-120425-70986-kajud0.gx679/node_modules/athena-ide-atom/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

```

And at the very end:

```
In file included from ../deps/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.cc:41:
In file included from ../deps/grpc/src/core/lib/security/credentials/jwt/jwt_credentials.h:25:
../deps/grpc/src/core/lib/security/credentials/jwt/json_token.h:27:10: fatal error: 'openssl/rsa.h' file not found
#include <openssl/rsa.h>
         ^~~~~~~~~~~~~~~
16 warnings and 1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/private/var/folders/3b/81d70l4s7_x_rrfjnzzbmgv00000gn/T/apm-install-dir-120425-70986-kajud0.gx679/node_modules/athena-ide-atom/node_modules/grpc/src/node/extension_binary/node-v45-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/private/var/folders/3b/81d70l4s7_x_rrfjnzzbmgv00000gn/T/apm-install-dir-120425-70986-kajud0.gx679/node_modules/athena-ide-atom/node_modules/grpc/src/node/extension_binary/node-v45-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v45"
gyp ERR! cwd /private/var/folders/3b/81d70l4s7_x_rrfjnzzbmgv00000gn/T/apm-install-dir-120425-70986-kajud0.gx679/node_modules/athena-ide-atom/node_modules/grpc
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
```

**Comment by kroggen** [comment]
On Mac the `openssl` is installed on an unconventional location.

You can run these commands on a terminal:

```
cd /usr/local/include/
ln -s /usr/local/opt/openssl/include/openssl openssl
```

And then try the installation again
